name: Test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: ['**']

jobs:
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v3
      - name: cargo-clippy
        run: cargo clippy --locked
