name: Dummy
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: ['**']

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Run dummy test
        run: echo "hello, world"
